from __future__ import annotations

from pathlib import Path


DATA_SNAPSHOT_PATH = Path("data/source_snapshot.json")

CATEGORY_LABELS = {
    "TOTAL": "Total Market",
    "PV": "Passenger Vehicles",
    "2W": "Two-Wheelers",
    "3W": "Three-Wheelers",
    "CV": "Commercial Vehicles",
    "TRACTOR": "Tractors",
    "CE": "Construction Equipment",
    "EV": "EV",
    "EV_SUPPLY": "EV supply chain",
}

CATEGORY_ORDER = ["TOTAL", "PV", "2W", "3W", "CV", "TRACTOR", "CE", "EV"]
RETAIL_CATEGORY_ORDER = ["PV", "2W", "3W", "CV", "TRACTOR", "CE"]
WHOLESALE_CATEGORY_ORDER = ["PV", "2W", "3W"]

FUEL_ORDER = ["EV", "Hybrid", "CNG / LPG", "Petrol / Ethanol", "Diesel", "Hydrogen"]

CHART_COLORS = {
    "TOTAL": "#f4b06d",
    "PV": "#8ad8c7",
    "2W": "#7ca4ff",
    "3W": "#f28b61",
    "CV": "#cab0ff",
    "TRACTOR": "#d7c46f",
    "CE": "#9aa4b2",
    "EV": "#54d3a1",
    "Hybrid": "#c9d971",
    "CNG / LPG": "#6bc3ff",
    "Petrol / Ethanol": "#f3c98b",
    "Diesel": "#6f7f95",
    "Hydrogen": "#bfcaf5",
}

VAHAN_STATE_SOURCE_URL = "https://analytics.parivahan.gov.in/analytics/publicdashboard/vahan?lang=en"
VAHAN_CLASS_MARKET_SOURCE_URL = "https://dataful.in/datasets/18262/"

STATE_REGISTRATION_TYPE_MAP = {
    "PV": (
        "Motor Car",
        "Adapted Vehicle",
        "Omni Bus (Private Use)",
        "Camper Van / Trailer",
        "Camper Van / Trailer (Private Use)",
        "Motor Caravan",
        "Private Service Vehicle (Individual Use)",
        "Quadricycle (Private)",
        "Trailer For Personal Use",
    ),
    "2W": (
        "M-Cycle/Scooter",
        "M-Cycle/Scooter-With Side Car",
        "Moped",
        "Motor Cycle/Scooter-Sidecar(T)",
        "Motor Cycle/Scooter-Used For Hire",
        "Motor Cycle/Scooter-With Trailer",
        "Motorised Cycle (Cc > 25Cc)",
        "Motorised Cycle (Cc > 25cc)",
    ),
    "3W": (
        "E-Rickshaw With Cart (G)",
        "E-Rickshaw(P)",
        "Three Wheeler (Goods)",
        "Three Wheeler (Passenger)",
        "Three Wheeler (Personal)",
    ),
    "CV": (
        "Ambulance",
        "Animal Ambulance",
        "Armoured/Specialised Vehicle",
        "Articulated Vehicle",
        "Auxiliary Trailer",
        "Breakdown Van",
        "Bus",
        "Cash Van",
        "Educational Institution Bus",
        "Fire Fighting Vehicle",
        "Fire Tenders",
        "Goods Carrier",
        "Hearses",
        "Library Van",
        "Luxury Cab",
        "Maxi Cab",
        "Mobile Canteen",
        "Mobile Clinic",
        "Mobile Workshop",
        "Modular Hydraulic Trailer",
        "Motor Cab",
        "Omni Bus",
        "Private Service Vehicle",
        "Quadricycle (Commercial)",
        "Recovery Vehicle",
        "Semi-Trailer (Commercial)",
        "Snorked Ladders",
        "Tow Truck",
        "Tower Wagon",
        "Trailer (Commercial)",
        "Vehicle Fitted With Compressor",
        "Vehicle Fitted With Generator",
        "Vehicle Fitted With Rig",
        "X-Ray Van",
    ),
}

SEGMENT_SHARE_CLASS_MAP = {
    "TOTAL": {
        "label": "Total market",
        "groups": [
            {"id": "PV", "label": "Passenger Vehicles", "classes": STATE_REGISTRATION_TYPE_MAP["PV"]},
            {"id": "2W", "label": "Two-Wheelers", "classes": STATE_REGISTRATION_TYPE_MAP["2W"]},
            {"id": "3W", "label": "Three-Wheelers", "classes": STATE_REGISTRATION_TYPE_MAP["3W"]},
            {"id": "CV", "label": "Commercial Vehicles", "classes": STATE_REGISTRATION_TYPE_MAP["CV"]},
            {
                "id": "TRACTOR",
                "label": "Tractors / farm",
                "classes": (
                    "Agricultural Tractor",
                    "Tractor (Commercial)",
                    "Trailer (Agricultural)",
                    "Tractor-Trolley(Commercial)",
                    "Harvester",
                    "Power Tiller",
                    "Power Tiller (Commercial)",
                ),
            },
            {
                "id": "CE",
                "label": "Construction equipment",
                "classes": (
                    "Construction Equipment Vehicle",
                    "Construction Equipment Vehicle (Commercial)",
                    "Earth Moving Equipment",
                    "Excavator (Commercial)",
                    "Excavator (Nt)",
                    "Crane Mounted Vehicle",
                    "Dumper",
                    "Fork Lift",
                    "Road Roller",
                    "Bulldozer",
                    "Modular Hydraulic Trailer",
                    "Tree Trimming Vehicle",
                ),
            },
        ],
    },
    "2W": {
        "label": "Two-Wheelers",
        "groups": [
            {
                "id": "motorcycles_scooters",
                "label": "Motorcycles / scooters",
                "classes": (
                    "M-Cycle/Scooter",
                    "M-Cycle/Scooter-With Side Car",
                    "Motor Cycle/Scooter-Sidecar(T)",
                    "Motor Cycle/Scooter-Used For Hire",
                    "Motor Cycle/Scooter-With Trailer",
                    "Scooter",
                ),
            },
            {"id": "moped", "label": "Mopeds", "classes": ("Moped",)},
            {
                "id": "motorised_cycle",
                "label": "Motorised cycles >25cc",
                "classes": (
                    "Motorised Cycle (Cc > 25Cc)",
                    "Motorised Cycle (Cc > 25cc)",
                ),
            },
        ],
    },
    "3W": {
        "label": "Three-Wheelers",
        "groups": [
            {"id": "three_w_passenger", "label": "3W passenger", "classes": ("Three Wheeler (Passenger)",)},
            {"id": "e_rickshaw_passenger", "label": "E-rickshaw passenger", "classes": ("E-Rickshaw(P)",)},
            {"id": "three_w_goods", "label": "3W goods", "classes": ("Three Wheeler (Goods)",)},
            {"id": "e_rickshaw_goods", "label": "E-rickshaw goods", "classes": ("E-Rickshaw With Cart (G)",)},
            {"id": "three_w_personal", "label": "3W personal", "classes": ("Three Wheeler (Personal)",)},
        ],
    },
    "CV": {
        "label": "Commercial Vehicles",
        "groups": [
            {"id": "goods_carrier", "label": "Goods carriers", "classes": ("Goods Carrier",)},
            {
                "id": "cabs_passenger",
                "label": "Cabs / passenger carriers",
                "classes": (
                    "Motor Cab",
                    "Maxi Cab",
                    "Ambulance",
                    "Luxury Cab",
                    "Private Service Vehicle",
                    "Private Service Vehicle (Individual Use)",
                    "Animal Ambulance",
                ),
            },
            {
                "id": "buses",
                "label": "Buses",
                "classes": (
                    "Bus",
                    "Educational Institution Bus",
                    "Omni Bus",
                    "Omni Bus (Private Use)",
                ),
            },
            {
                "id": "special_application",
                "label": "Special application CVs",
                "classes": (
                    "Articulated Vehicle",
                    "Auxiliary Trailer",
                    "Breakdown Van",
                    "Cash Van",
                    "Fire Fighting Vehicle",
                    "Fire Tenders",
                    "Hearses",
                    "Library Van",
                    "Mobile Canteen",
                    "Mobile Clinic",
                    "Mobile Workshop",
                    "Recovery Vehicle",
                    "Semi-Trailer (Commercial)",
                    "Tow Truck",
                    "Tower Wagon",
                    "Trailer (Commercial)",
                    "Vehicle Fitted With Compressor",
                    "Vehicle Fitted With Generator",
                    "Vehicle Fitted With Rig",
                    "X-Ray Van",
                    "Armoured/Specialised Vehicle",
                ),
            },
        ],
    },
    "TRACTOR": {
        "label": "Tractors / farm",
        "groups": [
            {"id": "agri_tractor", "label": "Agricultural tractors", "classes": ("Agricultural Tractor",)},
            {"id": "commercial_tractor", "label": "Commercial tractors", "classes": ("Tractor (Commercial)",)},
            {
                "id": "trailers",
                "label": "Agricultural trailers / trolley",
                "classes": (
                    "Trailer (Agricultural)",
                    "Tractor-Trolley(Commercial)",
                ),
            },
            {
                "id": "harvest_power",
                "label": "Harvesters / power tillers",
                "classes": (
                    "Harvester",
                    "Power Tiller",
                    "Power Tiller (Commercial)",
                ),
            },
        ],
    },
    "CE": {
        "label": "Construction equipment",
        "groups": [
            {
                "id": "construction_vehicle",
                "label": "Construction equipment vehicles",
                "classes": (
                    "Construction Equipment Vehicle",
                    "Construction Equipment Vehicle (Commercial)",
                ),
            },
            {
                "id": "earthmoving_excavators",
                "label": "Earthmoving / excavators",
                "classes": (
                    "Earth Moving Equipment",
                    "Excavator (Commercial)",
                    "Excavator (Nt)",
                ),
            },
            {
                "id": "cranes_material",
                "label": "Cranes / material handling",
                "classes": (
                    "Crane Mounted Vehicle",
                    "Fork Lift",
                ),
            },
            {
                "id": "heavy_specials",
                "label": "Dumpers / rollers / bulldozers",
                "classes": (
                    "Dumper",
                    "Road Roller",
                    "Bulldozer",
                    "Modular Hydraulic Trailer",
                    "Tree Trimming Vehicle",
                ),
            },
        ],
    },
}

LISTED_COMPANY_MAP = {
    "Maruti Suzuki": {
        "categories": ["PV", "CV"],
        "lens": ["retail", "wholesale"],
        "summary": "Mass-market PV leader with a smaller LCV presence in retail data.",
        "management_commentary": "Management said Q3 FY26 saw a sharp recovery in the Indian car market, led mainly by small cars after the GST reform. The company highlighted record domestic sales, record total sales and continued export momentum, signalling confidence that demand breadth has improved rather than being limited to premium segments.",
        "management_source_url": "https://www.marutisuzuki.com/corporate/media/press-releases/2026/january/maruti-suzuki-india-limited-financial-results-q3-and-9m-fy-2025-26",
        "management_source_label": "Q3 FY26 results",
    },
    "Tata Motors": {
        "categories": ["PV", "CV"],
        "lens": ["retail", "wholesale", "ev"],
        "summary": "Key listed proxy for PV, CV and electric passenger vehicles.",
        "management_commentary": "In the latest official CV-side Q3 FY26 update after the business restructuring, management said healthy demand across key segments and tighter execution are translating into profitable growth, double-digit margins and strong free cash flow. The company also said it remains confident of delivering on its stated financial guidance.",
        "management_source_url": "https://cv.tatamotors.com/news/tata-motors-limited-formerly-tml-commercial-vehicles-ltd-q3-fy26-results",
        "management_source_label": "Q3 FY26 CV results",
    },
    "Mahindra & Mahindra": {
        "categories": ["PV", "3W", "CV", "TRACTOR"],
        "lens": ["retail", "ev"],
        "summary": "Diversified exposure across UVs, LCVs, 3W last-mile mobility and tractors.",
        "management_commentary": "Management said Auto and Farm maintained leadership on the back of steady customer demand, strong product acceptance and disciplined execution. On the Q3 FY26 callout, it highlighted better SUV and LCV share, a still-dominant tractor franchise and a very positive early response to new launches.",
        "management_source_url": "https://www.mahindra.com/news-room/press-release/en/m-and-m-results-q3-f26",
        "management_source_label": "Q3 F26 results",
    },
    "Hyundai Motor India": {
        "categories": ["PV"],
        "lens": ["retail", "wholesale"],
        "summary": "Important listed PV benchmark for compact SUVs and premium hatchbacks.",
        "management_commentary": "Management said Hyundai is leaning further into SUV-led premiumisation while widening its ICE, CNG and EV portfolio. The FY25 annual report also framed Talegaon, Chennai EV capacity, and 26 model upgrades and launches through FY30 as the next leg of volume and mix growth.",
        "management_source_url": "https://www.hyundai.com/content/dam/hyundai/in/en/images/investor-relations/annualreports/annual-report2024-25.pdf",
        "management_source_label": "Annual report FY25",
    },
    "Hero MotoCorp": {
        "categories": ["2W"],
        "lens": ["retail"],
        "summary": "Largest listed 2W retail proxy in commuter motorcycles and scooters.",
        "management_commentary": "Management said Q3 FY26 delivered healthy double-digit volume and retail momentum, helped by improving rural demand and a supportive GST tailwind. The company said its focus remains on mix improvement, scooters, premium products, VIDA electric mobility and broader international expansion.",
        "management_source_url": "https://www.heromotocorp.com/content/dam/hero-aem-website/in/en-in/company-section/press-releases/2026/february-pdfs/press_release_hero_motocorp_q3fy26_results_feb_5_2026_i.pdf",
        "management_source_label": "Q3 FY26 results",
    },
    "TVS Motor": {
        "categories": ["2W", "3W"],
        "lens": ["retail", "ev"],
        "summary": "Broad 2W exposure plus 3W participation and e-2W optionality.",
        "management_commentary": "Management said growth in Q3 FY26 was broad-based across motorcycles, scooters, exports, three-wheelers and EVs, with each of those legs contributing to record sales, revenue and profit. The read-through is that the company still sees room to compound through both domestic premiumisation and international momentum.",
        "management_source_url": "https://www.tvsmotor.com/media/press-release/tvs-motor-highest-ever-sales-revenue-profits-q3fy26",
        "management_source_label": "Q3 FY26 results",
    },
    "Bajaj Auto": {
        "categories": ["2W", "3W"],
        "lens": ["retail", "ev"],
        "summary": "Strong listed proxy for both motorcycles and 3W passenger/goods demand.",
        "management_commentary": "Management described Q3 FY26 as a record quarter, driven by double-digit growth across domestic motorcycles, electric two-wheelers, three-wheelers and exports. It also highlighted that the electric portfolio reached about a quarter of domestic revenues, while Chetak and e-3W momentum improved sharply after supply bottlenecks eased.",
        "management_source_url": "https://www.bajajauto.com/-/media/images/bajajauto/media-kit/press-release/financial-quarterly/2026/bse-outcome-of-q3-results-bal.pdf",
        "management_source_label": "Q3 FY26 results",
    },
    "Eicher Motors": {
        "categories": ["2W", "TRACTOR", "CV"],
        "lens": ["retail"],
        "summary": "Royal Enfield and VECV make it useful for premium 2W and CV cycles.",
        "management_commentary": "Management said Royal Enfield crossed one million annual sales with exports growing faster than domestic volumes, while overseas assembly and local-market expansion are improving long-term reach. On the CV side, VECV beat industry growth, delivered record volumes and strengthened its light and medium-duty truck position despite a mixed market backdrop.",
        "management_source_url": "https://www.eicher.in/content/dam/eicher-motors/investor/financial-and-reports/quarterly-results/press-release_may-14-2025.pdf",
        "management_source_label": "Q4 FY25 results",
    },
    "Ashok Leyland": {
        "categories": ["CV"],
        "lens": ["retail"],
        "summary": "Pure-play listed CV proxy with MHCV and bus exposure.",
        "management_commentary": "Management said the FY25 CV backdrop stayed supported by infrastructure activity, stronger rural demand, robust bus replacement and a recovery in export markets. It highlighted record profitability, highest-ever MHCV bus volumes, improving exports and fresh electric-truck deliveries as evidence that growth is broadening beyond a single sub-segment.",
        "management_source_url": "https://www.ashokleyland.com/backend/wp-content/uploads/2025/07/Annual-Report-FY-2024-25.pdf",
        "management_source_label": "Annual report FY25",
    },
    "Escorts Kubota": {
        "categories": ["TRACTOR", "CE"],
        "lens": ["retail"],
        "summary": "Direct listed play on tractors and construction equipment demand.",
        "management_commentary": "Management framed FY25 around sustained leadership in tractors while using construction equipment and other non-tractor businesses to diversify the revenue base. The annual report also pointed to dealer expansion, financing support in emerging markets and the Kubota partnership as key levers to strengthen premium utility tractors and long-term farm mechanisation demand.",
        "management_source_url": "https://static.escortskubota.com/new/pdf/2025/june/EKL_Annual_Report_FY_2024-25.pdf",
        "management_source_label": "Annual report FY25",
    },
    "Action Construction Equipment": {
        "categories": ["CE"],
        "lens": ["retail"],
        "summary": "Construction equipment demand proxy within official FADA data.",
        "management_commentary": "Management said FY25 growth remained led by the combined cranes, material handling and construction equipment segment, which grew meaningfully faster than the agriculture equipment business. The annual report also stressed a more agile operating model and faster alignment to customer demand, reinforcing ACE's core exposure to infrastructure and industrial equipment cycles.",
        "management_source_url": "https://www.ace-cranes.com/public/front/pdf/Annual%20Report%20FY%202024-25_ACE_FF.pdf",
        "management_source_label": "Annual report FY25",
    },
    "Atul Auto": {
        "categories": ["3W"],
        "lens": ["retail", "ev"],
        "summary": "Listed 3W niche exposure with potential benefit from last-mile demand.",
        "management_commentary": "Management said FY25 delivered robust growth in three-wheeler volumes, revenue and profitability, helped by stronger market penetration and better operating efficiency. It also highlighted improving exports and wider market expansion as signs that the company is participating in both domestic last-mile demand and overseas three-wheeler opportunities.",
        "management_source_url": "https://atulauto.co.in/wp-content/uploads/2025/08/Final_AtulAutoAR_2025_compressed.pdf",
        "management_source_label": "Annual report FY25",
    },
    "Exide Industries": {
        "categories": ["EV_SUPPLY"],
        "lens": ["ev", "components"],
        "summary": "Battery beneficiary from EV penetration and replacement demand.",
        "management_commentary": "Management said Q3 FY26 demand recovered strongly across auto OEM, replacement, inverter and industrial segments, with GST 2.0 helping automotive demand. The company also pointed to continued investment behind lithium-ion cells and a preference for profitable growth while preserving balance-sheet flexibility.",
        "management_source_url": "https://www.exideindustries.com/investors/stock-exchange-information.aspx",
        "management_source_label": "Q3 FY26 earnings call",
    },
    "Amara Raja Energy & Mobility": {
        "categories": ["EV_SUPPLY"],
        "lens": ["ev", "components"],
        "summary": "Battery and energy-storage proxy with EV transition leverage.",
        "management_commentary": "Management said growth is being driven by robust OEM demand in both 4W and 2W, healthy aftermarket volumes and rising realisation from exports, while the new-energy business is gaining traction in telecom and stationary applications. It also said the customer qualification plant for indigenous cell manufacturing should materially accelerate the company's lithium-ion roadmap.",
        "management_source_url": "https://www.amararaja.com/press_release/amara-raja-energy-mobility-reports-8-increase-in-revenue-over-previous-year-same-quarter-in-q2-fy26/",
        "management_source_label": "Q2 FY26 results",
    },
    "Sona BLW Precision Forgings": {
        "categories": ["EV_SUPPLY"],
        "lens": ["ev", "components"],
        "summary": "EV drivetrain content proxy tied to electrification mix gains.",
        "management_commentary": "Management said Sona Comstar is moving from a traditional component base toward intelligent mobility systems, with BEV revenue rising sharply and EV programmes continuing to scale. The FY25 annual report also underlined bigger bets in China, deeper R&D, and a broader mobility-solutions portfolio as the next growth drivers.",
        "management_source_url": "https://sonacomstar.com/annual-report-24-25/index.html",
        "management_source_label": "Annual report FY25",
    },
    "Bharat Forge": {
        "categories": ["CV", "EV_SUPPLY"],
        "lens": ["components"],
        "summary": "CV cycle plus component export and EV platform optionality.",
        "management_commentary": "Management said Bharat Forge is positioning less for a conventional cycle and more for structural shifts across automotive, defence, aerospace and industrials. The FY25 annual report highlighted growing traction in domestic passenger vehicles, interest from global customers under China-plus-one, and a large defence order book as the key read-through for future growth.",
        "management_source_url": "https://www.bharatforge.com/AR2025/index.html",
        "management_source_label": "Annual report FY25",
    },
    "Uno Minda": {
        "categories": ["PV", "2W", "EV_SUPPLY"],
        "lens": ["components"],
        "summary": "Broad content supplier across lighting, switches and new mobility programs.",
        "management_commentary": "Management said the Indian auto industry still has a strong growth runway and Uno Minda is positioning for that through localisation, export expansion and rising content in LED lighting, ADAS, EV systems and alternate-fuel products. It also flagged new wins in EV chargers, camera modules and CNG components as proof that the content story is widening beyond traditional auto cycles.",
        "management_source_url": "https://www.unominda.com/uploads/Investor/2025/Q3%20Earnings%20Call%20Transcript.pdf",
        "management_source_label": "Q3 FY26 earnings call transcript",
    },
    "Samvardhana Motherson": {
        "categories": ["PV", "CV", "EV_SUPPLY"],
        "lens": ["components"],
        "summary": "Large diversified component export proxy with OEM cycle sensitivity.",
        "management_commentary": "Management said demand tailwinds continue to come from rising vehicle content, premiumisation, SUVs and the accelerating hybrid and EV mix across major regions. The annual report also emphasised disciplined cost control, customer engagement and supply-chain agility as the way Motherson plans to convert that structural content growth into resilient earnings.",
        "management_source_url": "https://www.motherson.com/storage/Corporate%20Announcements/FY2025-26/Disclosure_Annual_Report_FY_2024-25-06Aug.pdf",
        "management_source_label": "Annual report FY25",
    },
    "JBM Auto": {
        "categories": ["CV", "EV_SUPPLY"],
        "lens": ["ev", "components"],
        "summary": "Bus and electric mobility exposure with public transport optionality.",
        "management_commentary": "Management said JBM is not just selling buses but building an end-to-end electric mobility ecosystem across buses, batteries, charging, software and mobility services. The FY25 annual report also highlighted growing scale in e-buses, strong auto-components execution and in-house EV aggregates as the core pillars of the next growth phase.",
        "management_source_url": "https://www.jbmbuses.com/wp-content/uploads/2025/08/JBM-Auto-Annual-Report-2024-25.pdf",
        "management_source_label": "Annual report FY25",
    },
    "Olectra Greentech": {
        "categories": ["CV", "EV_SUPPLY"],
        "lens": ["ev"],
        "summary": "Electric bus proxy rather than broad auto demand beta.",
        "management_commentary": "Management said Olectra's electric-bus strategy is increasingly about fleet reliability, route relevance and technology upgrades rather than just unit sales. The FY25 annual report pointed to over 2,600 deployed buses, strong monthly operating mileage, work on blade-battery buses and roughly a quarter of India's e-bus market share as proof of execution scale.",
        "management_source_url": "https://olectra.com/wp-content/uploads/Olectra-Annual-Report-2024-25.pdf",
        "management_source_label": "Annual report FY25",
    },
    "Greaves Cotton": {
        "categories": ["2W", "3W", "EV_SUPPLY"],
        "lens": ["ev", "components"],
        "summary": "Small but relevant e-mobility and last-mile ecosystem proxy.",
        "management_commentary": "Management said Greaves is building a fuel-agnostic, digitally integrated mobility ecosystem rather than relying on a single propulsion trend. The annual report and recent results commentary both point to growth in engineering and retail, deeper reach in tier-3 and tier-4 markets, and continued investment in EV solutions, components and last-mile applications.",
        "management_source_url": "https://greavescotton.com/wp-content/uploads/2025/07/Annual-Report-2024-25.pdf",
        "management_source_label": "Annual report FY25",
    },
}

OEM_TO_LISTED = {
    "Maruti Suzuki": ["Maruti Suzuki"],
    "Tata Motors": ["Tata Motors"],
    "Mahindra & Mahindra": ["Mahindra & Mahindra"],
    "Mahindra Group": ["Mahindra & Mahindra"],
    "Mahindra Tractors": ["Mahindra & Mahindra"],
    "Mahindra Last Mile Mobility": ["Mahindra & Mahindra"],
    "Swaraj": ["Mahindra & Mahindra"],
    "Hyundai Motor India": ["Hyundai Motor India"],
    "Hero MotoCorp": ["Hero MotoCorp"],
    "TVS Motor": ["TVS Motor"],
    "Bajaj Auto": ["Bajaj Auto"],
    "Royal Enfield": ["Eicher Motors"],
    "VE Commercial Vehicles": ["Eicher Motors"],
    "Ashok Leyland Group": ["Ashok Leyland"],
    "Escorts Kubota": ["Escorts Kubota"],
    "Escorts Kubota CE": ["Escorts Kubota"],
    "Action Construction Equipment": ["Action Construction Equipment"],
    "Atul Auto": ["Atul Auto"],
    "Ather Energy": [],
    "Ola Electric": [],
    "Honda Motorcycle & Scooter India": [],
    "Honda Cars India": [],
    "Toyota Kirloskar Motor": [],
    "Kia India": [],
    "Skoda Auto Volkswagen Group": [],
    "JSW MG Motor India": [],
    "Renault India": [],
    "Nissan Motor India": [],
    "Mercedes-Benz Group": [],
    "BMW India": [],
    "Jaguar Land Rover India": [],
    "BYD India": [],
}

MODULE_TITLES = {
    "summary": "Market Snapshot",
    "retail": "Retail Pulse",
    "registration": "Registration Lens",
    "wholesale": "Wholesale Lens",
    "components": "Components",
    "credit_pulse": "Credit Pulse",
    "premium_data": "Premium Data Sources",
    "festive_pulse": "Festive Pulse",
    "recent_launches": "Recent Launches",
    "insights": "What Matters",
}

# Hand-curated calendar of the major retail-driving Indian festivals each
# year. Indian auto demand is heavily festive-led — Dhanteras and Diwali in
# particular are the single biggest car / 2W buying days. Dates shift every
# year because they follow the Hindu lunar calendar; we maintain three
# years of context (prior, current, next) so the dashboard can show timing.
FESTIVE_CALENDAR = {
    "2024": [
        {"name": "Onam", "date": "2024-09-15", "region": "Kerala", "tone": "regional"},
        {"name": "Ganesh Chaturthi", "date": "2024-09-07", "region": "Maharashtra / Karnataka", "tone": "regional"},
        {"name": "Navratri (start)", "date": "2024-10-03", "region": "Pan-India", "tone": "national"},
        {"name": "Dussehra", "date": "2024-10-12", "region": "Pan-India", "tone": "national"},
        {"name": "Karva Chauth", "date": "2024-10-20", "region": "North India", "tone": "regional"},
        {"name": "Dhanteras", "date": "2024-10-29", "region": "Pan-India", "tone": "peak"},
        {"name": "Diwali", "date": "2024-10-31", "region": "Pan-India", "tone": "peak"},
        {"name": "Bhai Dooj", "date": "2024-11-03", "region": "North / West India", "tone": "regional"},
    ],
    "2025": [
        {"name": "Akshaya Tritiya", "date": "2025-04-30", "region": "Pan-India", "tone": "national"},
        {"name": "Onam", "date": "2025-09-05", "region": "Kerala", "tone": "regional"},
        {"name": "Ganesh Chaturthi", "date": "2025-08-27", "region": "Maharashtra / Karnataka", "tone": "regional"},
        {"name": "Navratri (start)", "date": "2025-09-22", "region": "Pan-India", "tone": "national"},
        {"name": "Dussehra", "date": "2025-10-02", "region": "Pan-India", "tone": "national"},
        {"name": "Karva Chauth", "date": "2025-10-10", "region": "North India", "tone": "regional"},
        {"name": "Dhanteras", "date": "2025-10-18", "region": "Pan-India", "tone": "peak"},
        {"name": "Diwali", "date": "2025-10-20", "region": "Pan-India", "tone": "peak"},
        {"name": "Bhai Dooj", "date": "2025-10-23", "region": "North / West India", "tone": "regional"},
    ],
    "2026": [
        {"name": "Akshaya Tritiya", "date": "2026-04-19", "region": "Pan-India", "tone": "national"},
        {"name": "Ganesh Chaturthi", "date": "2026-08-15", "region": "Maharashtra / Karnataka", "tone": "regional"},
        {"name": "Onam", "date": "2026-08-26", "region": "Kerala", "tone": "regional"},
        {"name": "Navratri (start)", "date": "2026-09-12", "region": "Pan-India", "tone": "national"},
        {"name": "Dussehra", "date": "2026-09-21", "region": "Pan-India", "tone": "national"},
        {"name": "Karva Chauth", "date": "2026-10-29", "region": "North India", "tone": "regional"},
        {"name": "Dhanteras", "date": "2026-11-06", "region": "Pan-India", "tone": "peak"},
        {"name": "Diwali", "date": "2026-11-08", "region": "Pan-India", "tone": "peak"},
        {"name": "Bhai Dooj", "date": "2026-11-11", "region": "North / West India", "tone": "regional"},
    ],
}

PREMIUM_DATA_SOURCES = [
    {
        "id": "vahan-paid",
        "name": "Vahan / Parivahan Analytics API",
        "tier": "Government · NIC",
        "tagline": "The single biggest unlock — turns four currently-disabled dashboard tabs into live feeds.",
        "status": "blocked",
        "status_label": "Blocked from cloud runners",
        "color": "red",
        "currently_unlocks": [
            "Vahan retail registrations (state-wise)",
            "State-wise Vahan registrations",
            "Vahan EV registrations (live, state + RTO)",
            "EV trade tracker (live, currently hardcoded Mar 2026)",
        ],
        "what_you_get": [
            "Daily / monthly registrations at state, RTO and PIN-code level",
            "Vehicle class × fuel type matrix (PV / 2W / 3W / CV / Tractor / CE × Petrol / Diesel / EV / CNG / Hybrid)",
            "OEM × model registrations with verified VIN-level audit trail",
            "Same dataset MoRTH / SIAM / FADA all reconcile against",
        ],
        "cost": "₹25,000 – ₹2,00,000 / year",
        "cost_note": "Tiered by call volume and granularity. Contact NIC Vahan Help Desk.",
        "cta_label": "Vahan analytics",
        "cta_url": "https://analytics.parivahan.gov.in/analytics/",
    },
    {
        "id": "ev-trade-paid",
        "name": "Department of Commerce EV Trade Data",
        "tier": "Government · DGFT",
        "tagline": "Live HSN-code monthly EV import / export figures — the source for the EV trade tracker tile.",
        "status": "partial",
        "status_label": "Currently hardcoded",
        "color": "amber",
        "currently_unlocks": [
            "EV trade tracker (replaces the static Mar 2026 snapshot with live monthly updates)",
        ],
        "what_you_get": [
            "Monthly export and import volumes + USD value at HSN-8 granularity",
            "Country-wise trade splits (top 20 destinations)",
            "Lithium-ion cell, motor, BMS and full-vehicle line items",
        ],
        "cost": "₹35,000 – ₹1,50,000 / year",
        "cost_note": "DGFT ICEGATE bulk-data subscription, billed per HSN bucket.",
        "cta_label": "DGFT data subscription",
        "cta_url": "https://www.dgft.gov.in/CP/?opt=ft-data",
    },
    {
        "id": "jato",
        "name": "JATO Dynamics — India",
        "tier": "Industry · Subscription",
        "tagline": "Model-level pricing, specs and configuration data; the spine of any \"price index\" or \"feature index\" view.",
        "status": "absent",
        "status_label": "Not yet integrated",
        "color": "blue",
        "currently_unlocks": [
            "Model-launch tracker (planned)",
            "Price elasticity & MSRP index (planned)",
            "Feature-set comparison tooling (planned)",
        ],
        "what_you_get": [
            "OEM × model × variant master with MSRP, ex-showroom, on-road",
            "Spec sheets (engine, dimensions, ADAS features, safety ratings)",
            "Daily incentive / discount tracking per dealer geography",
        ],
        "cost": "$10,000 – $50,000 / year",
        "cost_note": "Approx. ₹8–40 lakh. Tier depends on data depth.",
        "cta_label": "JATO India",
        "cta_url": "https://www.jato.com/india/",
    },
    {
        "id": "polk",
        "name": "S&P Global Mobility (Polk)",
        "tier": "Industry · Enterprise",
        "tagline": "The institutional benchmark for verified registrations + forecasting.",
        "status": "absent",
        "status_label": "Not yet integrated",
        "color": "purple",
        "currently_unlocks": [
            "Independent cross-check on FADA retail",
            "Model-level OEM market-share tooling",
            "5-year forecast overlay on every monthly chart",
        ],
        "what_you_get": [
            "Verified VIN-anchored registrations covering 95%+ of India PV / CV",
            "Monthly market-share at OEM, brand and model level",
            "Production forecasts (LMC Automotive merge) by plant and platform",
        ],
        "cost": "$25,000 – $100,000 / year",
        "cost_note": "Approx. ₹20–80 lakh. Enterprise-only.",
        "cta_label": "S&P Mobility",
        "cta_url": "https://www.spglobal.com/mobility/en/products/automotive-data.html",
    },
    {
        "id": "crisil",
        "name": "CRISIL & ICRA — Auto Sector Reports",
        "tier": "Research · Credit Agencies",
        "tagline": "Quarterly outlook, OEM credit watch, and segment-level demand forecasts.",
        "status": "absent",
        "status_label": "Not yet integrated",
        "color": "teal",
        "currently_unlocks": [
            "Credit-agency outlook badge on each OEM tab",
            "Sector-level upgrade / downgrade alerts",
            "Forward-looking volume guidance overlays",
        ],
        "what_you_get": [
            "Quarterly Auto Industry Outlook PDF (segment + OEM commentary)",
            "Credit ratings & outlook changes for listed OEMs / ancillaries",
            "Monthly view-points and short notes on sector themes (EV, premium, exports)",
        ],
        "cost": "₹3,00,000 – ₹10,00,000 / year",
        "cost_note": "Per-report ₹50K–2L; annual seats from ~₹3L.",
        "cta_label": "CRISIL Research",
        "cta_url": "https://www.crisil.com/en/home/our-businesses/india-research.html",
    },
]


COMPANY_UNIT_TRENDS = {
    "Maruti Suzuki": {
        "label": "Maruti Suzuki",
        "concept": "Company-reported total monthly sales (domestic + OEM + exports)",
        "source_name": "Maruti Suzuki press releases",
        "series": [
            {"month": "2025-10", "units": 220894, "source_url": "https://www.marutisuzuki.com/corporate/media/press-releases/2025/november/maruti-suzuki-sales-in-october-2025"},
            {"month": "2025-11", "units": 229021, "source_url": "https://www.marutisuzuki.com/corporate/media/press-releases/2025/december/maruti-suzuki-sales-in-november-2025"},
            {"month": "2025-12", "units": 217854, "source_url": "https://www.marutisuzuki.com/corporate/media/press-releases/2026/january/maruti-suzuki-sales-in-december"},
            {"month": "2026-01", "units": 236963, "source_url": "https://www.marutisuzuki.com/corporate/media/press-releases/2026/february/maruti-suzuki-sales-in-january-2026"},
            {"month": "2026-02", "units": 213995, "source_url": "https://www.marutisuzuki.com/corporate/media/press-releases/2026/march/maruti-suzuki-sales-in-february-2026"},
            {"month": "2026-03", "units": 225251, "source_url": "https://www.marutisuzuki.com/corporate/media/press-releases/2026/april/maruti-suzuki-sales-in-march-2026-and-fy-2025-26"},
        ],
    },
    "Mahindra & Mahindra": {
        "label": "Mahindra & Mahindra",
        "concept": "Company-reported overall monthly auto sales (auto only; excludes tractors)",
        "source_name": "Mahindra auto monthly press releases",
        "series": [
            {"month": "2025-10", "units": 120142, "source_url": "https://www.mahindra.com/news-room/press-release/en/mahindra-auto-records-highest-ever-suv-sales-of-71624-vehicles-31-percent-growth-and-highest-ever-total-volumes-of-120142-in-october-2025"},
            {"month": "2025-11", "units": 92670, "source_url": "https://www.mahindra.com/news-room/press-release/en/mahindra-auto-clocks-56336-suvs-and-92670-total-vehicle-sales-in-november-2025"},
            {"month": "2025-12", "units": 86090, "source_url": "https://www.mahindra.com/news-room/press-release/en/mahindra-auto-clocks-50946-suvs-and-86090-total-vehicle-sales-in-december-2025"},
            {"month": "2026-01", "units": 104309, "source_url": "https://www.mahindra.com/news-room/press-release/en/mahindra-auto-clocks-63510-SUVs-and-104309-total-vehicle-sales-in-january-2026"},
            {"month": "2026-02", "units": 97177, "source_url": "https://www.mahindra.com/news-room/press-release/en/mahindra-auto-clocks-60018-suvs-and-97177-total-vehicle-sales-in-february-2026"},
            {"month": "2026-03", "units": 99969, "source_url": "https://www.mahindra.com/news-room/press-release/en/mahindra-auto-clocks-60272-suvs-and-99969-total-vehicle-sales-in-march-2026"},
        ],
    },
    "Hero MotoCorp": {
        "label": "Hero MotoCorp",
        "concept": "Company-reported monthly dispatches of motorcycles and scooters",
        "source_name": "Hero MotoCorp monthly sales releases",
        "series": [
            {"month": "2025-10", "units": 635808, "source_url": "https://www.heromotocorp.com/content/dam/hero-aem-website/in/en-in/company-section/press-releases/2025/october-pdf/press_release_hero_motocorp_celebrates_festive_season_with_nearly_10_lakh_million_retails_in_october_2025.pdf"},
            {"month": "2025-11", "units": 604490, "source_url": "https://www.heromotocorp.com/content/dam/hero-aem-website/in/en-in/company-section/press-releases/2025/december-pdfs/press_releasehero_motocorp_delivers_31percent_dispatch_growth_in_november_2025_driven_by_continued_festive_momentum.pdf"},
            {"month": "2025-12", "units": 456479, "source_url": "https://www.heromotocorp.com/content/dam/hero-aem-website/in/en-in/company-section/reports-and-polices/fillings-and-reports/press-releases/2025-2026/StxintimationPR01012026.pdf"},
            {"month": "2026-01", "units": 557871, "source_url": "https://www.heromotocorp.com/content/dam/hero-aem-website/in/en-in/company-section/press-releases/2026/january-pdfs/press_release_records_26_percent_dispatch_growth_with_5.58_lakh_units_sold_in_january_2026.pdf"},
            {"month": "2026-02", "units": 558216, "source_url": "https://www.heromotocorp.com/content/dam/hero-aem-website/in/en-in/company-section/press-releases/2026/march-pdfs/press_release_hero_motocorp_february_2026_sales_march_1_2026.pdf"},
            {"month": "2026-03", "units": 598198, "source_url": "https://www.heromotocorp.com/en-in/company/newsroom/press-release-news-and-media.html"},
        ],
    },
    "TVS Motor": {
        "label": "TVS Motor",
        "concept": "Company-reported monthly sales (2W + 3W, including exports)",
        "source_name": "TVS Motor monthly sales releases",
        "series": [
            {"month": "2025-10", "units": 543557, "source_url": "https://www.tvsmotor.com/Media/Press-Release/tvs-motor-company-achieves-its-highest-ever-monthly-sales-in-october-2025"},
            {"month": "2025-11", "units": 519508, "source_url": "https://www.tvsmotor.com/Media/Press-Release/tvs-motor-company-sales-grows-30-percent-november-2025"},
            {"month": "2025-12", "units": 481389, "source_url": "https://www.tvsmotor.com/media/press-release/tvs-motor-highest-ever-sales-revenue-profits-q3fy26"},
            {"month": "2026-01", "units": 511766, "source_url": "https://www.tvsmotor.com/Media/Press-Release/tvs-motor-company-sales-grow-29-percent-january-2026"},
            {"month": "2026-02", "units": 529308, "source_url": "https://www.tvsmotor.com/Media/Press-Release/tvs-motor-company-sales-grows-31-percent-in-february-2026"},
            {"month": "2026-03", "units": 519358, "source_url": "https://www.tvsmotor.com/Media/Press-Release/tvs-motor-company-sales-grow-25-percent-march-2026"},
        ],
    },
    "Bajaj Auto": {
        "label": "Bajaj Auto",
        "concept": "Company-reported monthly sales (2W + CV, domestic + exports)",
        "source_name": "Bajaj Auto monthly sales reports",
        "series": [
            {"month": "2025-10", "units": 518170, "source_url": "https://www.bajajauto.com/report/bajaj-report-2025.html"},
            {"month": "2025-11", "units": 453273, "source_url": "https://www.bajajauto.com/report/bajaj-report-2025.html"},
            {"month": "2025-12", "units": 369809, "source_url": "https://www.bajajauto.com/-/media/images/bajajauto/media-kit/press-release/2025/press-release-dec-2025.pdf"},
            {"month": "2026-01", "units": 477422, "source_url": "https://www.bajajauto.com/report/bajaj-report-2026.html"},
            {"month": "2026-02", "units": 448259, "source_url": "https://www.bajajauto.com/report/bajaj-report-2026.html"},
            {"month": "2026-03", "units": 445377, "source_url": "https://www.bajajauto.com/report/bajaj-report-2026.html"},
        ],
    },
    "Hyundai Motor India": {
        "label": "Hyundai Motor India",
        "concept": "Company-reported quarterly wholesale volumes (domestic + exports)",
        "source_name": "Hyundai investor relations",
        "series": [
            {"label": "Q1 FY26", "units": 180399, "source_url": "https://www.hyundai.com/content/dam/hyundai/in/en/data/investor-relations/quaterly-financials/press-release-Q1FY26.pdf"},
            {"label": "Q2 FY26", "units": 190921, "source_url": "https://www.hyundai.com/content/dam/hyundai/in/en/data/investor-relations/quaterly-financials/press-release-Q2.pdf"},
            {"label": "Q3 FY26", "units": 195436, "source_url": "https://www.hyundai.com/in/en/hyundai-story/media-center/press-release/q3-and-9m-fy26-financial-results"},
        ],
    },
    "Eicher Motors": {
        "label": "Eicher Motors",
        "concept": "Company-reported Royal Enfield monthly motorcycle sales",
        "source_name": "Eicher Motors monthly sales releases",
        "series": [
            {"month": "2025-12", "units": 103574, "source_url": "https://www.eicher.in/content/dam/eicher-motors/investor/financial-and-reports/monthly-sales-volume/eml-monthly-sales-december-2025.pdf"},
            {"month": "2026-01", "units": 104322, "source_url": "https://www.eicher.in/content/dam/eicher-motors/investor/financial-and-reports/monthly-sales-volume/monthly-sales-of-eml-of-january-2026.pdf"},
            {"month": "2026-02", "units": 100905, "source_url": "https://www.eicher.in/content/dam/eicher-motors/investor/financial-and-reports/monthly-sales-volume/monthly-sales-of-eml-of-february-2026.pdf"},
            {"month": "2026-03", "units": 112334, "source_url": "https://www.eicher.in/content/dam/eicher-motors/investor/financial-and-reports/monthly-sales-volume/monthly-sales-of-eml-of-march-2026.pdf"},
        ],
    },
    "Tata Motors": {
        "label": "Tata Motors",
        "concept": "Company-reported Tata Motors CV monthly sales",
        "source_name": "Tata Motors CV monthly sales releases",
        "series": [
            {"month": "2025-12", "units": 42508, "source_url": "https://cv.tatamotors.com/news/tata-motors-delivers-strong-sales"},
            {"month": "2026-01", "units": 41549, "source_url": "https://cv.tatamotors.com/news/tata-motors-registered-total-sales-of-41549-commercial-vehicle-units-in-january-2026"},
            {"month": "2026-02", "units": 42940, "source_url": "https://cv.tatamotors.com/news/tata-motors-registered-32%25-growth-yoy-with-total-sales-of-42940-commercial-vehicle-units-in-february-2026"},
            {"month": "2026-03", "units": 47976, "source_url": "https://cv.tatamotors.com/news/tata-motors-records-17-percent-growth-in-commercial-vehicle-sales-in-march-2026"},
        ],
    },
    "Ashok Leyland": {
        "label": "Ashok Leyland",
        "concept": "Company-reported quarterly CV volumes cited in official results commentary",
        "source_name": "Ashok Leyland quarterly results",
        "series": [
            {"label": "Q1 FY26", "units": 44238, "source_url": "https://www.ashokleyland.com/backend/wp-content/uploads/2025/08/Q1FY-26.pdf"},
            {"label": "Q2 FY26", "units": 44004, "source_url": "https://www.ashokleyland.com/in/pressrelease/ashok-leyland-q2-pbt-up-23-at-rs-1083-cr-pat-all-time-high-of-rs-771-cr-ebitda-up-at-12-1-announces-100-interim-dividend-of-rs-1-per-share"},
        ],
    },
    "Escorts Kubota": {
        "label": "Escorts Kubota",
        "concept": "Company-reported quarterly tractor volumes",
        "source_name": "Escorts Kubota earnings presentations",
        "series": [
            {"label": "Q4 FY25", "units": 26633, "source_url": "https://static.escortskubota.com/new/pdf/2025/may/Q4FY25-Earning-PPT-Final.pdf"},
            {"label": "Q1 FY26", "units": 30581, "source_url": "https://static.escortskubota.com/new/pdf/2025/august/EKL_2025_08_04_Intimation_of_Earning_Presentation-Signed.pdf"},
        ],
    },
    "Action Construction Equipment": {
        "label": "Action Construction Equipment",
        "concept": "Company-reported quarterly sales volume for cranes, construction equipment and material handling equipment",
        "source_name": "ACE earnings presentations",
        "series": [
            {"label": "Q1 FY26", "units": 2337, "source_url": "https://www.ace-cranes.com/public/front/pdf/Earning%20Presentation%20Q1FY2026.pdf"},
            {"label": "Q2 FY26", "units": 2348, "source_url": "https://www.ace-cranes.com/public/front/pdf/Earning%20presentation%20Q2%20FY2026.pdf"},
            {"label": "Q3 FY26", "units": 2710, "source_url": "https://www.ace-cranes.com/public/front/pdf/Earning%20Presentation%20Q3%20FY%202026.pdf"},
        ],
    },
    "Atul Auto": {
        "label": "Atul Auto",
        "concept": "Company-reported monthly total three-wheeler sales (domestic + exports)",
        "source_name": "Atul Auto sales updates",
        "series": [
            {"month": "2025-12", "units": 3602, "source_url": "https://atulauto.co.in/wp-content/uploads/2026/01/Signed_Letter_SalesPerformance_BSE_NSE_December2025-003.pdf"},
            {"month": "2026-01", "units": 3606, "source_url": "https://atulauto.co.in/wp-content/uploads/2026/02/SignedLetter_SalesPerformance_BSE_NSE_January2026.pdf"},
        ],
    },
}
