from __future__ import annotations

COMPANY = {
    "company_name": "Archean Chemical Industries Limited",
    "short_name": "Archean",
    "ticker": "ACI",
    "exchange": "NSE / BSE",
    "display_name": "Archean Chemical Industries Limited Research Dashboard",
    "sector": "Specialty marine chemicals",
    "headquarters": "Chennai, Tamil Nadu, India",
    "primary_site": "Hajipir, Kutch district, Gujarat",
    "website": "https://www.archeanchemicals.com/",
    "latest_period": "Q3FY26",
    "latest_period_end": "2025-12-31",
    "latest_update_label": "Q3 FY26 / 9M FY26",
    "description": (
        "Archean is an India-based specialty marine chemicals producer built around the "
        "Hajipir brine resource, with bromine, industrial salt and downstream bromine "
        "derivatives as the core earnings engine and a wider strategic push into mud "
        "chemicals, compound semiconductors and zinc-bromide energy storage."
    ),
}

OVERVIEW_FACTS = {
    "export_share_pct": 79.0,
    "largest_customer_pct": 41.0,
    "top_10_customer_pct": 77.0,
    "top_20_customer_pct": 89.0,
    "top_10_relationships_over_5y": 7,
    "domestic_clients": 41,
    "global_clients": 36,
    "bromine_backlog_tons": 6500,
    "salt_guidance_mt": 4.5,
    "sojitz_offtake_mtpa": 2200000,
    "notes": [
        {
            "title": "What changed this quarter?",
            "body": (
                "Industrial salt volumes recovered back above the 1 million ton quarterly run "
                "rate, while bromine remained held back by plant efficiency issues rather than "
                "demand weakness."
            ),
            "source_id": "archean-q3fy26-transcript",
        },
        {
            "title": "What matters next?",
            "body": (
                "The biggest near-term swing factor is bromine normalization: management said "
                "demand and the order book remain healthy, but output has to catch up."
            ),
            "source_id": "archean-q3fy26-transcript",
        },
        {
            "title": "Structural support",
            "body": (
                "Salt remains a throughput stabilizer with long-term export contracts, while "
                "Acume and SOP are the internal levers for value-chain upgrade rather than "
                "current headline earnings."
            ),
            "source_id": "archean-q2fy26-transcript",
        },
    ],
}

OVERVIEW_REVENUE_MIX_HISTORY = [
    {
        "period": "FY22",
        "label": "FY22",
        "period_type": "annual",
        "source_id": "archean-ar-fy23",
        "note": "Annual report view based on standalone product revenue.",
        "segments": [
            {"name": "Bromine", "revenue_mn": 6052.84, "status": "reported"},
            {"name": "Industrial Salt", "revenue_mn": 5128.99, "status": "reported"},
            {"name": "Sulphate of Potash", "revenue_mn": 113.99, "status": "reported"},
            {"name": "Other / new businesses", "revenue_mn": 8.58, "status": "derived"},
        ],
    },
    {
        "period": "FY23",
        "label": "FY23",
        "period_type": "annual",
        "source_id": "archean-ar-fy23",
        "note": "Annual report view based on standalone product revenue.",
        "segments": [
            {"name": "Bromine", "revenue_mn": 7083.92, "status": "reported"},
            {"name": "Industrial Salt", "revenue_mn": 7281.27, "status": "reported"},
            {"name": "Sulphate of Potash", "revenue_mn": 30.55, "status": "reported"},
            {"name": "Other / new businesses", "revenue_mn": 14.96, "status": "derived"},
        ],
    },
    {
        "period": "FY24",
        "label": "FY24",
        "period_type": "annual",
        "source_id": "archean-ar-fy25",
        "note": "Annual report comparative view from the FY25 annual report.",
        "segments": [
            {"name": "Bromine", "revenue_mn": 4274.3, "status": "reported"},
            {"name": "Industrial Salt", "revenue_mn": 8400.6, "status": "reported"},
            {"name": "Sulphate of Potash", "revenue_mn": 359.6, "status": "reported"},
            {"name": "Other / new businesses", "revenue_mn": 261.33, "status": "derived"},
        ],
    },
    {
        "period": "FY25",
        "label": "FY25",
        "period_type": "annual",
        "source_id": "archean-ar-fy25",
        "note": "Annual report view based on standalone product revenue.",
        "segments": [
            {"name": "Bromine", "revenue_mn": 3531.3, "status": "reported"},
            {"name": "Industrial Salt", "revenue_mn": 6594.8, "status": "reported"},
            {"name": "Sulphate of Potash", "revenue_mn": 9.7, "status": "reported"},
            {"name": "Other / new businesses", "revenue_mn": 2.1, "status": "derived"},
        ],
    },
    {
        "period": "9MFY26",
        "label": "9M FY26",
        "period_type": "nine_months",
        "source_id": "archean-q3fy26-presentation",
        "note": "Nine-month view. Bromine and salt are reported directly; the residual bucket covers the rest.",
        "segments": [
            {"name": "Bromine", "revenue_mn": 2146.5, "status": "reported"},
            {"name": "Industrial Salt", "revenue_mn": 5329.8, "status": "reported"},
            {"name": "Sulphate of Potash", "revenue_mn": 0.0, "status": "not_disclosed"},
            {"name": "Other / new businesses", "revenue_mn": 364.1, "status": "derived"},
        ],
    },
]

CUSTOMER_DISCLOSURE = [
    {
        "rank_label": "1",
        "customer_name": "Sojitz",
        "country": "Japan",
        "business": "Trading conglomerate",
        "sales_exposure_pct": 41.0,
        "disclosure_status": "Publicly named",
        "note": "Company presentation identifies Sojitz as the largest customer.",
        "source_id": "archean-q3fy26-presentation",
    },
    {
        "rank_label": "Top 2 to Top 10",
        "customer_name": "Not publicly disclosed",
        "country": "Mixed; not individually disclosed",
        "business": "Industrial customers",
        "sales_exposure_pct": 36.0,
        "disclosure_status": "Names not publicly disclosed",
        "note": "The company gives concentration percentages, but not the individual names. Seven of the top 10 customer relationships are older than five years.",
        "source_id": "archean-q3fy26-presentation",
    },
]

COMPANY_QUARTERLY_FINANCIALS = [
    {
        "period": "Q4FY25",
        "period_end": "2025-03-31",
        "period_type": "quarter",
        "reported_basis": "standalone",
        "revenue_total": 3333.4,
        "ebitda": 1011.2,
        "ebitda_margin": 30.3,
        "pat": 583.0,
        "depreciation": 186.3,
        "finance_cost": 29.1,
        "tax": 212.7,
        "other_expenses": 2232.0,
        "employee_cost": 144.7,
        "material_cost": 77.2,
        "inventory_change": -131.9,
        "source_id": "archean-q1fy26-presentation",
        "source_note": "Derived as FY25 full year minus 9MFY25 reported figures.",
        "status": "derived",
    },
    {
        "period": "Q1FY26",
        "period_end": "2025-06-30",
        "period_type": "quarter",
        "reported_basis": "standalone",
        "revenue_total": 2914.5,
        "ebitda": 958.0,
        "ebitda_margin": 32.9,
        "pat": 518.5,
        "depreciation": 198.2,
        "finance_cost": 44.6,
        "tax": 196.6,
        "other_expenses": 1663.6,
        "employee_cost": 165.0,
        "material_cost": 144.5,
        "inventory_change": -181.8,
        "source_id": "archean-q1fy26-presentation",
        "source_note": "Standalone profit and loss statement.",
        "status": "reported",
    },
    {
        "period": "Q2FY26",
        "period_end": "2025-09-30",
        "period_type": "quarter",
        "reported_basis": "standalone",
        "revenue_total": 2317.8,
        "ebitda": 759.9,
        "ebitda_margin": 32.8,
        "pat": 384.6,
        "depreciation": 203.9,
        "finance_cost": 45.0,
        "tax": 126.4,
        "other_expenses": 1503.5,
        "employee_cost": 144.2,
        "material_cost": 103.8,
        "inventory_change": -193.6,
        "source_id": "archean-q2fy26-presentation",
        "source_note": "Standalone profit and loss statement.",
        "status": "reported",
    },
    {
        "period": "Q3FY26",
        "period_end": "2025-12-31",
        "period_type": "quarter",
        "reported_basis": "standalone",
        "revenue_total": 2608.1,
        "ebitda": 698.6,
        "ebitda_margin": 26.8,
        "pat": 343.0,
        "depreciation": 203.7,
        "finance_cost": 37.4,
        "tax": 114.5,
        "other_expenses": 1803.7,
        "employee_cost": 150.3,
        "material_cost": 106.4,
        "inventory_change": -151.0,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "Standalone profit and loss statement.",
        "status": "reported",
    },
    {
        "period": "FY25",
        "period_end": "2025-03-31",
        "period_type": "annual",
        "reported_basis": "standalone",
        "revenue_total": 10634.5,
        "ebitda": 3721.2,
        "ebitda_margin": 35.0,
        "pat": 1849.2,
        "depreciation": 730.6,
        "finance_cost": 91.1,
        "tax": 648.4,
        "other_expenses": 6658.0,
        "employee_cost": 539.3,
        "material_cost": 388.8,
        "inventory_change": -672.9,
        "source_id": "archean-q1fy26-presentation",
        "source_note": "FY25 standalone annual totals presented in Q1 FY26 deck.",
        "status": "reported",
    },
    {
        "period": "9MFY26",
        "period_end": "2025-12-31",
        "period_type": "nine_months",
        "reported_basis": "standalone",
        "revenue_total": 7840.4,
        "ebitda": 2416.5,
        "ebitda_margin": 30.8,
        "pat": 1246.1,
        "depreciation": 605.9,
        "finance_cost": 126.9,
        "tax": 437.5,
        "other_expenses": 4970.9,
        "employee_cost": 459.6,
        "material_cost": 354.7,
        "inventory_change": -526.4,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "9MFY26 standalone totals.",
        "status": "reported",
    },
    {
        "period": "Q4FY25",
        "period_end": "2025-03-31",
        "period_type": "quarter",
        "reported_basis": "consolidated",
        "revenue_total": 3533.8,
        "ebitda": 961.0,
        "ebitda_margin": 27.2,
        "pat": 537.4,
        "depreciation": 211.3,
        "finance_cost": 2.8,
        "tax": 209.3,
        "other_expenses": 2253.4,
        "employee_cost": 195.9,
        "material_cost": 228.7,
        "inventory_change": -105.2,
        "source_id": "archean-q1fy26-presentation",
        "source_note": "Derived as FY25 full year minus 9MFY25 reported figures.",
        "status": "derived",
    },
    {
        "period": "Q1FY26",
        "period_end": "2025-06-30",
        "period_type": "quarter",
        "reported_basis": "consolidated",
        "revenue_total": 3005.9,
        "ebitda": 863.2,
        "ebitda_margin": 28.7,
        "pat": 401.4,
        "depreciation": 229.4,
        "finance_cost": 53.8,
        "tax": 178.6,
        "other_expenses": 1697.4,
        "employee_cost": 187.3,
        "material_cost": 340.6,
        "inventory_change": -247.9,
        "source_id": "archean-q1fy26-presentation",
        "source_note": "Consolidated profit and loss statement.",
        "status": "reported",
    },
    {
        "period": "Q2FY26",
        "period_end": "2025-09-30",
        "period_type": "quarter",
        "reported_basis": "consolidated",
        "revenue_total": 2395.6,
        "ebitda": 689.8,
        "ebitda_margin": 28.8,
        "pat": 290.4,
        "depreciation": 235.5,
        "finance_cost": 55.2,
        "tax": 108.7,
        "other_expenses": 1536.0,
        "employee_cost": 168.5,
        "material_cost": 126.7,
        "inventory_change": -125.4,
        "source_id": "archean-q2fy26-presentation",
        "source_note": "Consolidated profit and loss statement.",
        "status": "reported",
    },
    {
        "period": "Q3FY26",
        "period_end": "2025-12-31",
        "period_type": "quarter",
        "reported_basis": "consolidated",
        "revenue_total": 2615.2,
        "ebitda": 613.5,
        "ebitda_margin": 23.5,
        "pat": 240.0,
        "depreciation": 236.0,
        "finance_cost": 44.2,
        "tax": 93.3,
        "other_expenses": 1838.0,
        "employee_cost": 173.0,
        "material_cost": 154.3,
        "inventory_change": -163.6,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "Consolidated profit and loss statement.",
        "status": "reported",
    },
    {
        "period": "FY25",
        "period_end": "2025-03-31",
        "period_type": "annual",
        "reported_basis": "consolidated",
        "revenue_total": 10783.0,
        "ebitda": 3514.4,
        "ebitda_margin": 32.6,
        "pat": 1621.4,
        "depreciation": 793.8,
        "finance_cost": 81.0,
        "tax": 616.2,
        "other_expenses": 6736.0,
        "employee_cost": 610.5,
        "material_cost": 629.4,
        "inventory_change": -707.3,
        "source_id": "archean-q1fy26-presentation",
        "source_note": "FY25 consolidated annual totals presented in Q1 FY26 deck.",
        "status": "reported",
    },
    {
        "period": "9MFY26",
        "period_end": "2025-12-31",
        "period_type": "nine_months",
        "reported_basis": "consolidated",
        "revenue_total": 8016.7,
        "ebitda": 2166.5,
        "ebitda_margin": 27.0,
        "pat": 931.8,
        "depreciation": 700.9,
        "finance_cost": 153.2,
        "tax": 380.6,
        "other_expenses": 5071.4,
        "employee_cost": 528.9,
        "material_cost": 621.5,
        "inventory_change": -536.8,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "9MFY26 consolidated totals.",
        "status": "reported",
    },
]

COMPANY_SEGMENT_METRICS = [
    {
        "period": "Q3FY25",
        "period_end": "2024-12-31",
        "period_type": "quarter",
        "product_segment": "Bromine",
        "revenue": 930.0,
        "volume_tons": 4614,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "Q3FY25 bromine revenue and volume from comparative slide.",
        "status": "reported",
    },
    {
        "period": "Q3FY25",
        "period_end": "2024-12-31",
        "period_type": "quarter",
        "product_segment": "Industrial Salt",
        "revenue": 1491.0,
        "volume_tons": 758796,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "Q3FY25 salt revenue and volume from comparative slide.",
        "status": "reported",
    },
    {
        "period": "Q1FY26",
        "period_end": "2025-06-30",
        "period_type": "quarter",
        "product_segment": "Bromine",
        "revenue": 840.0,
        "volume_tons": 4054,
        "source_id": "archean-q1fy26-transcript",
        "source_note": "Management disclosed Q1 bromine revenue of INR84 crore and volume of 4,054 tons.",
        "status": "reported",
    },
    {
        "period": "Q1FY26",
        "period_end": "2025-06-30",
        "period_type": "quarter",
        "product_segment": "Industrial Salt",
        "revenue": 1940.0,
        "volume_tons": 1100000,
        "source_id": "archean-q1fy26-transcript",
        "source_note": "Management disclosed Q1 salt revenue of INR194 crore and sales volume of 1.1 million tons.",
        "status": "reported",
    },
    {
        "period": "Q1FY26",
        "period_end": "2025-06-30",
        "period_type": "quarter",
        "product_segment": "Sulphate of Potash",
        "revenue": 2.6,
        "volume_tons": 52,
        "source_id": "archean-q1fy26-transcript",
        "source_note": "Management disclosed SOP revenue of INR26 lakhs and volume of 52 tons.",
        "status": "reported",
    },
    {
        "period": "Q2FY26",
        "period_end": "2025-09-30",
        "period_type": "quarter",
        "product_segment": "Bromine",
        "revenue": 720.0,
        "volume_tons": 3160,
        "source_id": "archean-q2fy26-transcript",
        "source_note": "Management disclosed Q2 bromine revenue of INR72 crores and sales volume of 3,160 tons.",
        "status": "reported",
    },
    {
        "period": "Q2FY26",
        "period_end": "2025-09-30",
        "period_type": "quarter",
        "product_segment": "Industrial Salt",
        "revenue": 1480.0,
        "volume_tons": 889193,
        "source_id": "archean-q2fy26-transcript",
        "source_note": "Management disclosed Q2 industrial salt revenue of INR148 crores and sales volume of 889,193 tons.",
        "status": "reported",
    },
    {
        "period": "Q3FY26",
        "period_end": "2025-12-31",
        "period_type": "quarter",
        "product_segment": "Bromine",
        "revenue": 579.0,
        "volume_tons": 2403,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "Q3FY26 bromine revenue and volume from standalone segment slide.",
        "status": "reported",
    },
    {
        "period": "Q3FY26",
        "period_end": "2025-12-31",
        "period_type": "quarter",
        "product_segment": "Industrial Salt",
        "revenue": 1913.0,
        "volume_tons": 1063848,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "Q3FY26 industrial salt revenue and volume from standalone segment slide.",
        "status": "reported",
    },
    {
        "period": "Q3FY26",
        "period_end": "2025-12-31",
        "period_type": "quarter",
        "product_segment": "Bromine Derivatives",
        "revenue": 137.0,
        "volume_tons": 799,
        "source_id": "archean-q3fy26-transcript",
        "source_note": "Management disclosed Acume Q3 revenue of INR137 million and volume of 799 tons.",
        "status": "reported",
    },
    {
        "period": "Q3FY26",
        "period_end": "2025-12-31",
        "period_type": "quarter",
        "product_segment": "Sulphate of Potash",
        "revenue": 3.2,
        "volume_tons": 71,
        "source_id": "archean-q3fy26-transcript",
        "source_note": "Management disclosed SOP Q3 revenue of INR32 lakhs and volume of 71 tons.",
        "status": "reported",
    },
    {
        "period": "9MFY26",
        "period_end": "2025-12-31",
        "period_type": "nine_months",
        "product_segment": "Bromine",
        "revenue": 2146.5,
        "volume_tons": 9531,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "9MFY26 bromine revenue and volume from highlights slide.",
        "status": "reported",
    },
    {
        "period": "9MFY26",
        "period_end": "2025-12-31",
        "period_type": "nine_months",
        "product_segment": "Industrial Salt",
        "revenue": 5329.8,
        "volume_tons": 3069238,
        "source_id": "archean-q3fy26-presentation",
        "source_note": "9MFY26 industrial salt revenue and volume from highlights slide.",
        "status": "reported",
    },
]

COMPANY_CAPACITY_UTILIZATION = [
    {
        "asset_name": "Hajipir bromine facility",
        "plant_location": "Hajipir, Kutch district, Gujarat",
        "product": "Bromine",
        "installed_capacity": 42500,
        "unit": "mtpa",
        "current_utilization": None,
        "historical_utilization": "Q3FY26 dispatch proxy: 22.6%; 9MFY26 dispatch proxy: 29.9%",
        "expansion_capacity": 0,
        "expected_commissioning": "Operational",
        "source_note": "42,500 MTPA installed; utilization shown only as dispatch proxy because production was not disclosed.",
        "source_id": "archean-crisil-fy25",
        "status": "reported",
    },
    {
        "asset_name": "Hajipir industrial salt complex",
        "plant_location": "Hajipir, Kutch district, Gujarat",
        "product": "Industrial Salt",
        "installed_capacity": 6000000,
        "unit": "tons",
        "current_utilization": None,
        "historical_utilization": "Q3FY26 dispatch proxy annualized: 70.9%; 9MFY26 dispatch proxy annualized: 68.2%",
        "expansion_capacity": 0,
        "expected_commissioning": "Expanded to 6.0 MT by FY25",
        "source_note": "CRISIL cites expansion from 4.8 MT to 6.0 MT; utilization is dispatch proxy only.",
        "source_id": "archean-crisil-fy25",
        "status": "reported",
    },
    {
        "asset_name": "Acume bromine derivatives facility",
        "plant_location": "Jhagadia, Gujarat",
        "product": "Bromine Derivatives",
        "installed_capacity": 18000,
        "unit": "mtpa",
        "current_utilization": None,
        "current_utilization_display": "30% to 40% reported band",
        "historical_utilization": "Management commentary: 30% to 40% in Q2 and Q3 FY26",
        "expansion_capacity": 10000,
        "expected_commissioning": "Phase 1 operational; phase 2 under evaluation",
        "source_note": "Acume total capacity 28,000 MTPA, with phase 1 at 18,000 MTPA and 30% to 40% current utilization band.",
        "source_id": "archean-q3fy26-transcript",
        "status": "estimated",
    },
    {
        "asset_name": "Jakhau jetty logistics chain",
        "plant_location": "Near Jakhau, Gujarat",
        "product": "Industrial Salt logistics",
        "installed_capacity": 5000000,
        "unit": "tons",
        "current_utilization": None,
        "historical_utilization": "Fair-weather operations from October to May",
        "expansion_capacity": 0,
        "expected_commissioning": "Operational",
        "source_note": "Jakhau fair-weather jetty with twin conveyor system and designed capacity of 5 million MT per annum.",
        "source_id": "archean-ar-fy25",
        "status": "reported",
    },
]

PLANT_ASSET_REGISTER = [
    {
        "plant_name": "Hajipir integrated marine chemicals complex",
        "state": "Gujarat",
        "exact_location": "Hajipir, Bhuj Taluk, Kutch district",
        "product_line": "Bromine, industrial salt, SOP",
        "process_description": "Natural sea brine from the Rann of Kutch is processed into salt, bromine and SOP.",
        "captive_power_or_energy_details": "Power intensity is high; company cites benefits from 66 kVA lines and lower power costs in FY24.",
        "water_dependency": "Directly dependent on brine concentration and seasonal monsoon dilution.",
        "logistics_dependency": "Integrated with Jakhau jetty and Mundra port access.",
        "project_status": "Operating core asset",
        "source_id": "archean-ar-fy25",
    },
    {
        "plant_name": "Jakhau jetty",
        "state": "Gujarat",
        "exact_location": "Near Hajipir / Jakhau coast",
        "product_line": "Industrial salt export logistics",
        "process_description": "Twin conveyor loading system for salt export cargo.",
        "captive_power_or_energy_details": "Not separately disclosed",
        "water_dependency": "Not material",
        "logistics_dependency": "Fair-weather closure during monsoon is a recurring bottleneck.",
        "project_status": "Operating",
        "source_id": "archean-ar-fy25",
    },
    {
        "plant_name": "Acume Chemicals bromine derivatives plant",
        "state": "Gujarat",
        "exact_location": "Jhagadia",
        "product_line": "CBF, HBr, inorganic and organic bromides",
        "process_description": "Forward-integration of captive bromine into oilfield, PTA and specialty bromide products.",
        "captive_power_or_energy_details": "Not separately disclosed",
        "water_dependency": "Standard chemical manufacturing utilities",
        "logistics_dependency": "Customer qualification pace is the bigger bottleneck than logistics.",
        "project_status": "Operational at 30% to 40% utilization and scaling customer approvals",
        "source_id": "archean-q3fy26-transcript",
        "source_ids": ["archean-ar-fy25", "archean-q3fy26-transcript"],
    },
    {
        "plant_name": "Idealis Mudchemie operating footprint",
        "state": "Andhra Pradesh / Gujarat / Tamil Nadu",
        "exact_location": "Strategic manufacturing and distribution points across three states",
        "product_line": "Customized drilling fluids, muds and chemicals",
        "process_description": "Oilfield chemical and mud manufacturing acquired through NCLT process.",
        "captive_power_or_energy_details": "Not separately disclosed",
        "water_dependency": "Standard industrial process dependency",
        "logistics_dependency": "Commercial ramp depends on customer approvals and oilfield demand.",
        "project_status": "Initial commercial operations started; customer samples and certifications still underway",
        "source_id": "archean-ar-fy25",
        "source_ids": ["archean-ar-fy25", "archean-q3fy26-presentation"],
    },
    {
        "plant_name": "SiCSem compound semiconductor fab",
        "state": "Odisha",
        "exact_location": "Infovalley-II, Bhubaneswar",
        "product_line": "Silicon carbide wafers and power devices",
        "process_description": "Integrated SiC compound semiconductor fabrication and packaging facility.",
        "captive_power_or_energy_details": "Not separately disclosed",
        "water_dependency": "Semiconductor-grade utility dependence expected",
        "logistics_dependency": "Project execution and supply-chain partner onboarding",
        "project_status": "ISM approved; site allotted and early ground work has started",
        "source_id": "archean-q3fy26-transcript",
    },
    {
        "plant_name": "Proposed Gujarat captive salt jetty",
        "state": "Gujarat",
        "exact_location": "Gujarat coast; exact site not yet disclosed",
        "product_line": "Industrial salt export logistics",
        "process_description": "Proposed 7 MMTPA captive salt jetty under the Gujarat MoU to support salt export handling.",
        "captive_power_or_energy_details": "Not separately disclosed",
        "water_dependency": "Coastal handling asset; no process-water dependency disclosed",
        "logistics_dependency": "Intended to reduce third-party handling dependence once approvals and execution are complete.",
        "project_status": "MoU signed; approvals and planning stage",
        "source_id": "archean-gujarat-jetty-mou-feb-2026",
    },
]

COMPANY_CAPEX_PROJECTS = [
    {
        "project_name": "Acume bromine derivatives phase 1",
        "business_segment": "Bromine Derivatives",
        "location": "Jhagadia, Gujarat",
        "capex_amount": 251.0,
        "status": "Operational / 30% to 40% utilization",
        "expected_start": "Operational since FY25; current focus is utilization ramp-up",
        "expected_completion": "Phase 1 is operational; management is targeting 50% to 60% utilization in the coming quarters",
        "expected_capacity_addition": "18,000 MTPA phase 1 within 28,000 MTPA total",
        "strategic_rationale": "Capture higher-value bromine integration and internalize captive demand.",
        "source": "archean-q3fy26-transcript",
    },
    {
        "project_name": "Acume flame retardants phase 2",
        "business_segment": "Bromine Derivatives",
        "location": "Jhagadia, Gujarat",
        "capex_amount": 250.0,
        "status": "Feasibility and launch-plan evaluation underway",
        "expected_start": "Detailed feasibility review and launch / ramp-up plan are in progress",
        "expected_completion": "Earlier 12 to 18 month / FY27 run-rate timeline still referenced; no formal revised date given",
        "expected_capacity_addition": "Not separately disclosed",
        "strategic_rationale": "Extend bromine derivatives portfolio into electronics and flame-retardant chemistry.",
        "source": "archean-q3fy26-transcript",
    },
    {
        "project_name": "Idealis Mudchemie refurbishment",
        "business_segment": "Mud Chemicals",
        "location": "Andhra Pradesh / Gujarat / Tamil Nadu",
        "capex_amount": 76.9,
        "status": "Commercial operations commenced at initial scale; samples and certifications ongoing",
        "expected_start": "Commercial start achieved; current phase is customer sampling and certifications",
        "expected_completion": "Phased scale-up through FY26 and beyond",
        "expected_capacity_addition": "Five units revived; exact rated capacity not disclosed",
        "strategic_rationale": "Build a broader oilfield chemistry basket alongside clear brine fluids.",
        "source": "archean-q3fy26-presentation",
    },
    {
        "project_name": "Gujarat captive salt jetty",
        "business_segment": "Industrial Salt logistics",
        "location": "Gujarat coastline",
        "capex_amount": None,
        "status": "MoU signed with Gujarat government",
        "expected_start": "Signed on January 30, 2026; approvals and facilitation are the next step",
        "expected_completion": "No commissioning date disclosed yet",
        "expected_capacity_addition": "7 MMTPA jetty throughput",
        "strategic_rationale": "Strengthen captive salt export logistics and reduce dependence on third-party handling.",
        "source": "archean-gujarat-jetty-mou-feb-2026",
    },
    {
        "project_name": "SiCSem compound semiconductor facility",
        "business_segment": "Semiconductor optionality",
        "location": "Infovalley-II, Bhubaneswar, Odisha",
        "capex_amount": 2067.0,
        "status": "FSA finalization and early site execution underway; long-lead machinery funding disclosed",
        "expected_start": "25-acre site allotted; land levelling complete; topographical survey and soil testing underway",
        "expected_completion": "Multi-year build; on March 26, 2026 Archean disclosed a Rs 260 cr loan to Neun Infra for long-lead machinery and equipment",
        "expected_capacity_addition": "60,000 wafers and 96 million packaging units annually",
        "strategic_rationale": "Create a SiC power-device platform tied to energy transition end markets.",
        "source": "archean-neun-loan-mar-2026",
    },
]

COMPANY_SUBSIDIARIES_AND_INVESTMENTS = [
    {
        "name": "Acume Chemicals Private Limited",
        "business": "Bromine derivatives",
        "stake": "100%",
        "status": "Operating / ramping",
        "strategic_link_to_core_bromine_business": "Direct forward integration of captive bromine into higher-value downstream products.",
        "revenue_stage": "Early commercial",
        "expected_scale_up": "Running at 30% to 40% now; management is targeting 50% to 60% in coming quarters.",
        "source": "archean-q3fy26-transcript",
    },
    {
        "name": "Idealis Chemicals Private Limited",
        "business": "Acquisition vehicle for mud chemicals",
        "stake": "100%",
        "status": "Merger approved into Idealis Mudchemie / pending implementation",
        "strategic_link_to_core_bromine_business": "Hosts the Oren / Mudchemie acquisition that complements oilfield chemistry.",
        "revenue_stage": "Holding structure pending merger",
        "expected_scale_up": "Board approved the merger of Idealis Chemicals into Idealis Mudchemie on March 19, 2026 to simplify the group structure and consolidate chemical and mud-chemical operations. The entity still exists separately until legal completion.",
        "source": "archean-idealis-merger-mar-2026",
    },
    {
        "name": "Neun Infra Private Limited",
        "business": "Holding company for SiCSem and semiconductor funding",
        "stake": "100%",
        "status": "Funding support in place / project holding structure",
        "strategic_link_to_core_bromine_business": "Not a direct bromine earnings arm; it houses the semiconductor platform and related funding.",
        "revenue_stage": "Pre-revenue / project SPV",
        "expected_scale_up": "Archean granted an additional Rs 6 cr loan on June 26, 2025, taking total Neun loans outstanding to Rs 73 cr to support the semiconductor business and silicon carbide research at IIT Bhubaneswar.",
        "source": "archean-neun-loan-jun-2025",
    },
    {
        "name": "Idealis Mudchemie Private Limited",
        "business": "Customized drilling fluids and mud chemicals",
        "stake": "100% indirect",
        "status": "Initial commercial operations / merger approved pending implementation",
        "strategic_link_to_core_bromine_business": "Broadens oilfield solutions alongside Acume clear brine fluids.",
        "revenue_stage": "Initial commercial revenue",
        "expected_scale_up": "Commercial operations have started at an initial scale and customer samples and certifications are ongoing. Archean also approved the merger of Idealis Chemicals into Idealis Mudchemie on March 19, 2026, with legal completion still pending.",
        "source": "archean-idealis-merger-mar-2026",
    },
    {
        "name": "SiCSem Private Limited",
        "business": "Silicon carbide compound semiconductor fabrication",
        "stake": "ACIL-led step-down subsidiary",
        "status": "Approved / early site execution",
        "strategic_link_to_core_bromine_business": "Strategic adjacency rather than direct bromine monetization.",
        "revenue_stage": "Optionality",
        "expected_scale_up": "ISM approval is in hand, the fiscal support agreement is being finalized, and site work has already started.",
        "source": "archean-q3fy26-presentation",
    },
    {
        "name": "Clas-SiC Wafer Fab Limited",
        "business": "SiC device technology and process modules",
        "stake": "22.24% fully diluted",
        "status": "Strategic technology investment",
        "strategic_link_to_core_bromine_business": "Supports the broader semiconductor platform rather than current bromine earnings.",
        "revenue_stage": "Strategic optionality",
        "expected_scale_up": "Investment is complete and secures technology access in India for the wider SiCSem build-out.",
        "source": "archean-q3fy26-presentation",
    },
    {
        "name": "Offgrid Energy Labs",
        "business": "Zinc-bromide energy storage",
        "stake": "18.14%",
        "status": "Strategic minority investment",
        "strategic_link_to_core_bromine_business": "Direct chemistry adjacency through zinc-bromide batteries.",
        "revenue_stage": "Pilot / optionality",
        "expected_scale_up": "18.14% stake is already secured, the investment is expected to complete in FY26, and the next step is a 10 MWh demo line in the U.K.",
        "source": "archean-q3fy26-presentation",
    },
]

PEER_METRICS = [
    {
        "peer_name": "ICL Industrial Products",
        "geography": "Global / Israel-led bromine chain",
        "bromine_exposure": "62% of FY25 sales mix",
        "segment_revenue": 1239.0,
        "segment_ebitda": 281.0,
        "segment_margin": 22.7,
        "production_commentary": "Eight production plants and number-one bromine capacity position.",
        "pricing_commentary": "Factsheet supports broad specialty bromine exposure rather than quarter-specific pricing guidance.",
        "volume_commentary": "Large, diversified industrial-products platform with ~1,320 customers.",
        "source": "icl-industrial-products-fy25",
    }
]

MARKET_CONTEXT_FALLBACK = {
    "bromine_price_context": {
        "source_id": "pricewatch-bromine-q4-2025",
        "headline": "Q4 2025 bromine regime remained firm",
        "body": (
            "Price-Watch described Q4 2025 bromine prices across India, Israel, Jordan and China "
            "as up roughly 9% to 20% quarter on quarter, helped by demand from flame retardants, "
            "agrochemicals, electronics and downstream intermediates."
        ),
        "covered_markets": ["FOB Mundra", "Ex Ahmedabad", "Ex Shandong", "FOB Haifa", "FOB Aqaba"],
        "date_published": "2026-03-23",
        "date_modified": "2026-03-26",
    }
}

IRAN_ISRAEL_WAR_2025 = {
    "id": "iran_israel_2025_window",
    "selector_label": "June 2025 war",
    "status": "Completed",
    "page_label": "Iran-Israel Event",
    "analysis_window_label": "June 13 to June 24, 2025",
    "analysis_scope_note": (
        "This page studies the June 13 to June 24, 2025 Israel-Iran war because it is the latest "
        "completed conflict window with enough price, trade and company data for a fair before-vs-after read."
    ),
    "timeline": [
        {
            "date": "2025-04-10",
            "title": "Risk was visible before the war",
            "detail": "ChemAnalyst said Israeli bromine prices were stable, but geopolitical risk and logistics uncertainty were already rising before the strikes.",
            "source_id": "chemanalyst-israel-bromine-apr-2025",
        },
        {
            "date": "2025-06-13",
            "title": "Israel launches strikes on Iran",
            "detail": "The June 13 strike starts the conflict window used in this page.",
            "source_id": "cfr-iran-israel-july-2025",
        },
        {
            "date": "2025-06-19",
            "title": "Shipping risk premium spikes",
            "detail": "Shell warned the conflict could have a huge trade impact, and tanker day-rates on the route jumped sharply.",
            "source_id": "guardian-shell-hormuz-june-2025",
        },
        {
            "date": "2025-06-24",
            "title": "Ceasefire closes the main war window",
            "detail": "This is the end date used for the event-window share-price and market comparison.",
            "source_id": "cfr-iran-israel-july-2025",
        },
        {
            "date": "2026-02-11",
            "title": "Archean says customers did not materially repivot",
            "detail": "Management said it had not heard any significant shift from customers toward India and saw no immediate upside from the conflict.",
            "source_id": "archean-q3fy26-transcript",
        },
    ],
    "share_price_window": [
        {"date": "2025-06-02", "close_price_inr": 616.10, "volume": 232040, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-03", "close_price_inr": 618.65, "volume": 65243, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-04", "close_price_inr": 628.35, "volume": 165064, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-05", "close_price_inr": 638.55, "volume": 256565, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-06", "close_price_inr": 642.20, "volume": 152661, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-09", "close_price_inr": 649.50, "volume": 300752, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-10", "close_price_inr": 641.55, "volume": 137002, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-11", "close_price_inr": 634.30, "volume": 99458, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-12", "close_price_inr": 631.60, "volume": 148147, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-13", "close_price_inr": 636.25, "volume": 132532, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-16", "close_price_inr": 633.85, "volume": 196418, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-17", "close_price_inr": 628.15, "volume": 122353, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-18", "close_price_inr": 619.80, "volume": 96112, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-19", "close_price_inr": 608.65, "volume": 92959, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-20", "close_price_inr": 633.05, "volume": 186154, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-23", "close_price_inr": 619.65, "volume": 157498, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-24", "close_price_inr": 615.70, "volume": 114755, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-25", "close_price_inr": 635.35, "volume": 142362, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-26", "close_price_inr": 631.05, "volume": 149964, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-27", "close_price_inr": 628.65, "volume": 64758, "source_id": "equitypandit-aci-history"},
        {"date": "2025-06-30", "close_price_inr": 632.60, "volume": 90338, "source_id": "equitypandit-aci-history"},
        {"date": "2025-07-01", "close_price_inr": 621.15, "volume": 83441, "source_id": "equitypandit-aci-history"},
        {"date": "2025-07-02", "close_price_inr": 619.25, "volume": 109651, "source_id": "equitypandit-aci-history"},
    ],
    "icl_industrial_products": [
        {"period": "Q1 2025", "sales_usd_mn": 344.0, "ebitda_usd_mn": 76.0, "ebitda_margin_pct": 22.1, "source_id": "icl-q1-2025-results"},
        {"period": "Q2 2025", "sales_usd_mn": 319.0, "ebitda_usd_mn": 69.0, "ebitda_margin_pct": 21.6, "source_id": "icl-q2-2025-results"},
        {"period": "Q3 2025", "sales_usd_mn": 295.0, "ebitda_usd_mn": 67.0, "ebitda_margin_pct": 22.7, "source_id": "icl-q3-2025-results"},
    ],
    "bromine_price_markets": [
        {"period": "Q2 2025", "market": "Jordan FOB Aqaba", "price_usd_per_ton": 2370.0, "comment": "Stable versus Q1 despite freight stress.", "source_id": "chemanalyst-bromine-2025"},
        {"period": "Q2 2025", "market": "USA FOB Houston", "price_usd_per_ton": 2630.0, "comment": "Prices rose, but the U.S. stayed insulated by domestic production.", "source_id": "chemanalyst-bromine-2025"},
        {"period": "Q3 2025", "market": "China", "price_usd_per_ton": 3392.0, "comment": "Supply constraints and freight kept prices firm.", "source_id": "chemanalyst-bromine-2025"},
        {"period": "Q3 2025", "market": "United Arab Emirates", "price_usd_per_ton": 2626.0, "comment": "Import tightness and Red Sea rerouting lifted landed costs.", "source_id": "chemanalyst-bromine-2025"},
        {"period": "Q4 2025", "market": "China", "price_usd_per_ton": 3861.0, "comment": "Prices moved materially higher by year-end.", "source_id": "chemanalyst-bromine-2025"},
        {"period": "Q4 2025", "market": "United Arab Emirates", "price_usd_per_ton": 2898.67, "comment": "Freight pressure eased, but prices remained firm.", "source_id": "chemanalyst-bromine-2025"},
    ],
}

IRAN_ISRAEL_WAR_2026_CURRENT = {
    "id": "iran_israel_2026_current",
    "selector_label": "Current war (2026)",
    "status": "Ongoing",
    "page_label": "Iran-Israel Event",
    "analysis_window_label": "February 28, 2026 to latest accessible market read",
    "analysis_scope_note": (
        "This page studies the current Iran-Israel war that began on February 28, 2026. "
        "Because the conflict is still ongoing, the dashboard separates hard market moves "
        "that can already be measured from trade and margin outcomes that still have not been reported."
    ),
    "data_cutoff_label": "Latest accessible market cut-off: March 24, 2026 for Archean share price; March 19, 2026 for the latest oil shock datapoint.",
    "timeline": [
        {
            "date": "2026-02-20",
            "title": "Market was already bracing for conflict",
            "detail": "Reuters said Brent had already reached a six-month high as traders worried that military action against Iran was getting closer.",
            "source_id": "reuters-iran-oil-risk-feb20-2026",
        },
        {
            "date": "2026-02-28",
            "title": "Current war begins",
            "detail": "Reuters said U.S. and Israeli strikes on Iran triggered the current conflict window used in this page.",
            "source_id": "reuters-iran-war-start-2026",
        },
        {
            "date": "2026-03-02",
            "title": "Shipping and oil react immediately",
            "detail": "Reuters said Brent jumped to as high as $82.37 and around 150 ships were stranded as shipping disruption spread through the Gulf.",
            "source_id": "reuters-oil-shipping-shock-2026",
        },
        {
            "date": "2026-03-06",
            "title": "Insurance support is expanded",
            "detail": "Reuters said the U.S. moved to reinsure Gulf maritime losses up to about $20 billion after tanker transit had ground to a halt.",
            "source_id": "reuters-maritime-reinsurance-2026",
        },
        {
            "date": "2026-03-12",
            "title": "War looked predictable to specialist risk desks",
            "detail": "Reuters reported that advisory firms were assigning high probabilities to military action before the strikes actually happened.",
            "source_id": "reuters-iran-war-predictability-2026",
        },
        {
            "date": "2026-03-13",
            "title": "Hormuz traffic collapse becomes measurable",
            "detail": "Reuters said traffic through the Strait of Hormuz had dropped 97% since the war began.",
            "source_id": "reuters-hormuz-closure-2026",
        },
        {
            "date": "2026-03-19",
            "title": "Energy facilities are hit and oil spikes again",
            "detail": "Reuters said Brent settled at $107.38 after strikes on major Middle East energy assets and kept rising after settlement.",
            "source_id": "reuters-oil-energy-facilities-mar19-2026",
        },
        {
            "date": "2026-03-24",
            "title": "Latest accessible Archean market read",
            "detail": "Archean's accessible historical price series had recovered above its pre-war close by March 24, but the company still had not reported a post-war quarter.",
            "source_id": "equitypandit-aci-history",
        },
    ],
    "share_price_window": [
        {"date": "2026-02-20", "close_price_inr": 559.80, "volume": 56437, "source_id": "equitypandit-aci-history"},
        {"date": "2026-02-23", "close_price_inr": 564.00, "volume": 60740, "source_id": "equitypandit-aci-history"},
        {"date": "2026-02-24", "close_price_inr": 574.75, "volume": 126671, "source_id": "equitypandit-aci-history"},
        {"date": "2026-02-25", "close_price_inr": 590.15, "volume": 121531, "source_id": "equitypandit-aci-history"},
        {"date": "2026-02-26", "close_price_inr": 596.00, "volume": 124686, "source_id": "equitypandit-aci-history"},
        {"date": "2026-02-27", "close_price_inr": 576.15, "volume": 229773, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-02", "close_price_inr": 551.10, "volume": 165835, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-04", "close_price_inr": 529.35, "volume": 157956, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-05", "close_price_inr": 538.15, "volume": 177809, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-06", "close_price_inr": 550.15, "volume": 109768, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-09", "close_price_inr": 531.20, "volume": 70871, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-10", "close_price_inr": 548.65, "volume": 109250, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-11", "close_price_inr": 537.20, "volume": 93423, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-12", "close_price_inr": 565.85, "volume": 248949, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-13", "close_price_inr": 592.10, "volume": 310257, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-16", "close_price_inr": 575.30, "volume": 239808, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-17", "close_price_inr": 566.30, "volume": 69522, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-18", "close_price_inr": 575.30, "volume": 161505, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-19", "close_price_inr": 574.50, "volume": 136336, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-20", "close_price_inr": 601.25, "volume": 237171, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-23", "close_price_inr": 612.15, "volume": 432463, "source_id": "equitypandit-aci-history"},
        {"date": "2026-03-24", "close_price_inr": 607.30, "volume": 187371, "source_id": "equitypandit-aci-history"},
    ],
    "oil_shock_window": [
        {"date": "2026-02-18", "label": "Pre-war scare", "brent_usd_per_bbl": 70.35, "source_id": "reuters-iran-oil-risk-feb18-2026"},
        {"date": "2026-02-20", "label": "Last full pre-war session", "brent_usd_per_bbl": 71.76, "source_id": "reuters-iran-oil-risk-feb20-2026"},
        {"date": "2026-03-02", "label": "First war shock", "brent_usd_per_bbl": 82.37, "source_id": "reuters-oil-shipping-shock-2026"},
        {"date": "2026-03-03", "label": "Second session", "brent_usd_per_bbl": 78.83, "source_id": "reuters-oil-supply-risk-mar3-2026"},
        {"date": "2026-03-16", "label": "Third-week settle", "brent_usd_per_bbl": 100.21, "source_id": "reuters-hormuz-oil-mar16-2026"},
        {"date": "2026-03-17", "label": "Rebound after pullback", "brent_usd_per_bbl": 102.69, "source_id": "reuters-oil-supply-risk-mar17-2026"},
        {"date": "2026-03-19", "label": "Energy-facility spike", "brent_usd_per_bbl": 107.38, "source_id": "reuters-oil-energy-facilities-mar19-2026"},
    ],
    "shipping_stress": [
        {"metric": "Ships stranded on March 2", "value": 150.0, "unit": "ships", "source_id": "reuters-oil-shipping-shock-2026"},
        {"metric": "Hormuz traffic drop by March 13", "value": 97.0, "unit": "%", "source_id": "reuters-hormuz-closure-2026"},
        {"metric": "Named vessels hit by March 12", "value": 15.0, "unit": "ships", "source_id": "reuters-ships-attacked-2026"},
        {"metric": "U.S. reinsurance support by March 6", "value": 20.0, "unit": "USD bn", "source_id": "reuters-maritime-reinsurance-2026"},
    ],
    "bromine_price_proxy": [
        {"period": "Feb 2026", "market": "Global bromine index", "price_usd_per_kg": 3.12, "status": "derived", "source_id": "businessanalytiq-bromine-mar-2026"},
        {"period": "Mar 2026", "market": "Global bromine index", "price_usd_per_kg": 3.15, "status": "reported", "source_id": "businessanalytiq-bromine-mar-2026"},
        {"period": "Feb 2026", "market": "Middle East bromine index", "price_usd_per_kg": 2.55, "status": "derived", "source_id": "businessanalytiq-bromine-mar-2026"},
        {"period": "Mar 2026", "market": "Middle East bromine index", "price_usd_per_kg": 2.54, "status": "reported", "source_id": "businessanalytiq-bromine-mar-2026"},
    ],
}

SCENARIO_LABELS = {
    "base": "Base",
    "bull": "Bull",
    "bear": "Bear",
}
